icon: ':simple-jellyfin:'
cit:
  mode: screenshot
  port: 8096
  wait: 300
  ready: "Startup complete"
  screenshot_wait: 10
  annotations:
    - org.freebsd.jail.allow.mlock=true

build:
  variants:
    - tag: pkg
      containerfile: Containerfile.pkg
      aliases: ["latest"]
      default: true
    - tag: pkg-latest
      containerfile: Containerfile.pkg
      args:
        BASE_VERSION: "15-latest"
